twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        [
            'bootstrap_5_layout.html.twig',
            'form/custom_types.html.twig'
        ]

    globals:
        gg_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        quantite_max_commande: '%env(QUANTITE_MAX_COMMANDE)%'
        stripe_pk: '%env(STRIPE_PK)%'
        stripe_sk: '%env(STRIPE_SK)%'

when@test:
    twig:
        strict_variables: true
